### PR TITLE
Update LoginTests.java

### PR DESCRIPTION
**Pull request by crpro108**

### CODE REVIEW

**Comment by Berichicko** [comment]
Please finish the homework!You got this problem, please correct it.

image

HINT

image

image

**Review by crpro108 — COMMENTED** [review]
line 16 (in LoginTests) is to omit the version error

**Comment by Berichicko** [comment]
The code is not compiled! Please finish the homework!You got this problem, please correct it.

image

**SOLUTION**

image

**Comment by crpro108** [comment]
Hi Alex, i have to add line 17 in my code (Homework16.java) otherwise i get a version error locally. What would you suggest in terms of submitting the homework?

**Comment by crpro108** [comment]
Screenshot 2024-02-29 at 8 58 00 AM

**Pull request merged**
